---
title: "___"
author: "___"
date: "`r format(Sys.time(), '%d %B, %Y')`"
bibliography: references.bib
output: html_document 
lang: "fr"
---

<!--# Complétez l'entête YAML.-->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
SciViews::R("model", lang = "fr")
```

# Introduction

Le développement du follicule ovarien et l'ovocyte sont coordonnées chez les mammifères [@wigglesworth2013]. L'hypoxanthine est une molécule présente dans le liquide folliculaire ainsi que dans l'ovocyte de la souris [@pan2019]. Cette molécule permet l'arrêt méoitique des ovocytes [@eppig1987].

# Analyse

<!--% Importez le tableau `ovocyte.rds` et assignez-le à `ovo`. Vérifiez le type des variables.-->

```{r import}

```

<!--% Réalisez un tableau et un graphique pertinent proposant la proportion d'ovocytes ayant maturé en fonction de la concentration d'hypoxanthine.-->

```{r tab}

```

```{r plot}

```

<!-- Interprétez le tableau et le graphique ci-dessus en 3 à 4 phrases maximum.-->

<!-- Réalisez un modèle linéaire généralisé pertinent de la variable `mat` en fonction de `conc`. Étudiez ce modèle à l'aide du résumé du modèle..-->

```{r glm}

```

<!-- Interprétez le modèle ci-dessus en 3 à 5 phrases maximum.-->

# Discussion et conclusions

<!--% Discutez de vos résultats et apportez des conclusions ici en 2 à 3 maximum.-->

<!--# Ne modifiez, ni n"écrivez rien ci-dessous. Les références seront automatiquement compilées à la fin du document après le titre "Références" -->

# Références {.unnumbered}
